### ISSUE TITLE
QRコード読み取ったとき投票者のIDとNameを表示するところがおかしい

### ISSUE THREAD

**Issue by ferretdayo** [tsukuba-pbl/16-4_Web#11]
投票者のQRコードを複数回読み込むと、表示するIDとNameがおかしい。
removeChildで毎回削除していこう

**Comment by Ikuzus-k** [comment]
QR読み込みエラーのときに alert() で読み込みエラーとだけ表示してて表示の empty() が行われていなかったのを修正した(pull request)。
現状、正しく認識されるQRコードは複数読み込んでも正しい表示が行われるはず。
